### ISSUE TITLE
Network meta-analysis on standardised mean difference

### ISSUE THREAD

**Issue by softloud** [softloud/adpain#54]
Hi @dmphillippo,

Thanks so much for helping out. You're a :star: 

Some of our outcomes are continuous and are on a dizzying variety of scales, so we can't present results as mean difference. Am I right in assuming I should do this?

1. Calculate smd with study comparator.
2. Create data frame with diff and diff_se where diff = smd if row is not a trt ref and NA if row is a trt ref, diff_se with square root of variance of smd if not a trt ref, and the se of the trt ref where the row is a trt ref.
3. Use `set_agd_contrast` to set up the network.
4. Run network through nma.

The network plot outputs but the model comes up empty. What am I doing wrong?

I've put an example in [**documentation/contrast-q.Rmd**](https://github.com/softloud/adpain/blob/main/documentation/contrast-q.Rmd) together with dataset: [**example-smd-dat.rds**](https://github.com/softloud/adpain/blob/main/example-smd-dat.rds). 

Also, if there is no placebo, i.e., trt ref for the entire network, in the study, is the comparator for that study chosen arbitrarily (as I am) or is there a more statistically cromulent way of choosing the trt ref for a study?

**Comment by dmphillippo** [comment]
Hi @softloud, my pleasure!

The steps you have described all sound correct to me. Looking at your output, the key part of the error message coming out of `nma()` is `agd_contrast_Sigma is not positive definite`. So the likelihood covariance matrix isn't being constructed correctly (ie. from the standard errors `se_diff`).

I'll take a closer look tomorrow and see if I can see what the exact problem is.

**Comment by dmphillippo** [comment]
I've taken a closer look, and I think there are a couple of issues here:

1. `escalc` only works for two-arm trials. For multi-arm trials, using `escalc` separately for each comparison results in different standardisation factors being used for the different comparisons, which results in inconsistent SMDs. We need to use the pooled SD from all arms to standardise all the contrasts in a multi-arm study. However, this is not actually the cause of this specific error...
2. The SE in the reference arm is used to define the covariance in multi-arm trials. Because we are standardising things, we need to apply the same standardisation factor to the SE in the reference arm. Using the unstandardised SE, as well as being incorrect, in this case results in an invalid covariance matrix (not positive definite).

I think you can achieve both of the above with the following:
```r
dat <- dat %>% 
  mutate(arm = 1:n(),
         mi = sum(n) - n(),
         cmi = exp(lgamma(mi/2) - log(sqrt(mi/2)) - lgamma((mi - 1)/2)),
         sdpool = sqrt(weighted.mean(sd^2, n - 1)),
         smd = if_else(arm == 1, NA_real_, (mean - first(mean)) / sdpool * cmi),
         se_smd = if_else(arm == 1,
                          se / sdpool * cmi,
                          sqrt((n + first(n))/(n * first(n)) + smd^2 / (2 * (n + first(n))))))
```
Because `dat` is grouped by `study` (and sorted by `intervention`, although we should get the same results in any sort order just against different reference arms), we can make use of `first()` to pull out the reference arm bits.

The SMD calculated is Hedges g, as per `escalc`, which makes a small-sample correction to the SMD and it's SE (`cmi`). You can see that we simply "standardise" the reference arm SE as `se / sdpool * cmi`. (The standardisation factor for each study is `cmi / sdpool`.)

Then we can set up the network and fit the `nma()` (note that you need to choose some priors).

```r
# set network
net <- 
  set_agd_contrast(
    data = dat,
    study = study,
    trt = intervention,
    y = smd,
    se = se_smd,
    sample_size = n,
    trt_ref = "placebo"
  ) 


# network plot
plot(net)

# fit model
mod <- 
  nma(
    net,
    trt_effects = "random"
    # need to add priors here
  )

mod
```

Does that all sound reasonable?

**Comment by dmphillippo** [comment]
Also, are you are setting `options(mc.cores = parallel::detectCores())` somewhere else, in order to run the models in parallel?

**Comment by softloud** [comment]
This is awesome, @dmphillippo. I will try coding this up and let you know how I go. 

I _was_ worried about the multiple arms per study thing! Was going to ask you if that was an issue.
